---
# tasks file for grafana

- name: Installing python
  apt:
    name: python3.6

- name: Adding key for grafana package
  shell: wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
  args:  
    warn: false

- name: Adding garafana package to repository
  command: add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"

- name: Installing grafana
  apt:
    name: grafana
    update_cache: yes

- name: daemon-reloading
  systemd:
    daemon_reload: yes

- name: Restarting grafana-server
  shell: systemctl start grafana-server
