---
# handlers file for kafka


- name: daemon reload
  systemd:
    daemon-reload: yes

- name: kafka restart
  service:
    name: kafka
    state: restarted

- name: zookeeper restart
  service:
    name: zookeeper
    state: restarted

