---
- name: Install_Dependency_Ansible 
  raw: sudo apt-get update

- name: Install_Dependency_Ansible 
  raw: sudo apt-get install python -y

- name: Install Unzip
  apt:
    name: unzip
    state: present

- name: Creating user for prometheus
  user: 
   name: prometheus
   shell: /bin/false

- name: Downloading the binary file for Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move the binary executable file
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus
    dest: /usr/local/bin/
    mode: 0555
    remote_src: yes

- name: Create directory for Prometheus Configuration and for Data dump
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Adding Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Copy Service for Prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  
- name: Daemon reload
  systemd: 
    daemon_reload: yes

- name: Start the Service
  service:
    name: prometheus 
    state: started

- name: Enable the Service
  service:
    name: prometheus 
    enabled: yes
  
- name: Update
  shell: sudo apt-get update
